# Generated by Django 5.0.6 on 2024-05-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_nickname',
            new_name='user_Nickname',
        ),
    ]
